export const books = [
    {
      id: 1,
      title: 'The Great Gatsby',
      image:'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471173936/the-great-gatsby-9781471173936_hr.jpg',
      author: 'F. Scott Fitzgerald',
      category: 'Fiction',
      description: 'A novel set in the 1920s, exploring themes of wealth and excess.',
      rating: 4.7,
    },
    {
      id: 2,
      title: '1984',
      image:'https://upload.wikimedia.org/wikipedia/en/5/51/1984_first_edition_cover.jpg',
      author: 'George Orwell',
      category: 'Fiction',
      description: 'A dystopian novel about totalitarianism and surveillance.',
      rating: 4.8,
    },
    {
      id: 3,
      title: 'The Martian',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/The_Martian_%28Weir_novel%29.jpg/220px-The_Martian_%28Weir_novel%29.jpg',
      author: 'Andy Weir',
      category: 'Sci-Fi',
      description: 'A science fiction novel about an astronaut stranded on Mars.',
      rating: 4.6,
    },
    {
      id: 4,
      title: 'Sapiens',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/0/06/%E1%B8%B2itsur_toldot_ha-enoshut.jpg/220px-%E1%B8%B2itsur_toldot_ha-enoshut.jpg',
      author: 'Yuval Noah Harari',
      category: 'Non-Fiction',
      description: 'A brief history of humankind, exploring our evolution and impact.',
      rating: 4.5,
    },
    {
      id: 5,
      title: 'To Kill a Mockingbird',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/220px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg',
      author: 'Harper Lee',
      category: 'Fiction',
      description: 'A story of racial injustice in the Deep South.',
      rating: 4.9,
    },
    {
      id: 6,
      title: 'Pride and Prejudice',
      image:'https://i.pinimg.com/736x/0a/91/4d/0a914d521dd1f37449d2a40510529181.jpg',
      author: 'Jane Austen',
      category: 'Fiction',
      description: 'A classic romance about love and social standing.',
      rating: 4.8,
    },
    {
      id: 7,
      title: 'The Catcher in the Rye',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg/220px-The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg',
      author: 'J.D. Salinger',
      category: 'Fiction',
      description: 'A coming-of-age story of teenage rebellion.',
      rating: 4.2,
    },
    {
      id: 8,
      title: 'Brave New World',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/6/62/BraveNewWorld_FirstEdition.jpg/220px-BraveNewWorld_FirstEdition.jpg',
      author: 'Aldous Huxley',
      category: 'Sci-Fi',
      description: 'A futuristic novel about a controlled society.',
      rating: 4.3,
    },
    {
      id: 9,
      title: 'Educated',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Educated_%28Tara_Westover%29.png/220px-Educated_%28Tara_Westover%29.png',
      author: 'Tara Westover',
      category: 'Non-Fiction',
      description: 'A memoir of a young woman who grows up in a strict, abusive household.',
      rating: 4.7,
    },
    {
      id: 10,
      title: 'The Road',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/The-road.jpg/220px-The-road.jpg',
      author: 'Cormac McCarthy',
      category: 'Fiction',
      description: 'A post-apocalyptic journey of a father and son.',
      rating: 4.5,
    },
    {
      id: 11,
      title: 'Becoming',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Becoming_%28Michelle_Obama_book%29.jpg/220px-Becoming_%28Michelle_Obama_book%29.jpg',
      author: 'Michelle Obama',
      category: 'Non-Fiction',
      description: 'A memoir by the former First Lady of the United States.',
      rating: 4.8,
    },
    {
      id: 12,
      title: 'Dune',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/d/de/Dune-Frank_Herbert_%281965%29_First_edition.jpg/220px-Dune-Frank_Herbert_%281965%29_First_edition.jpg',
      author: 'Frank Herbert',
      category: 'Sci-Fi',
      description: 'An epic saga of a desert planet and its people.',
      rating: 4.6,
    },
    {
      id: 13,
      title: 'The Hobbit',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/TheHobbit_FirstEdition.jpg/220px-TheHobbit_FirstEdition.jpg',
      author: 'J.R.R. Tolkien',
      category: 'Fantasy',
      description: 'A prelude to the Lord of the Rings, about a hobbit’s adventure.',
      rating: 4.7,
    },
    {
      id: 14,
      title: 'Moby-Dick',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Moby-Dick_FE_title_page.jpg/220px-Moby-Dick_FE_title_page.jpg',
      author: 'Herman Melville',
      category: 'Fiction',
      description: 'The tale of a captain’s obsessive quest for revenge.',
      rating: 4.1,
    },
    {
      id: 15,
      title: 'The Immortal Life of Henrietta Lacks',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/The_Immortal_Life_Henrietta_Lacks_%28cover%29.jpg/220px-The_Immortal_Life_Henrietta_Lacks_%28cover%29.jpg',
      author: 'Rebecca Skloot',
      category: 'Non-Fiction',
      description: 'The story of a woman whose cells changed medical research.',
      rating: 4.6,
    },
    {
      id: 16,
      title: 'The Alchemist',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/TheAlchemist.jpg/220px-TheAlchemist.jpg',
      author: 'Paulo Coelho',
      category: 'Fiction',
      description: 'A philosophical tale of following one’s dreams.',
      rating: 4.4,
    },
    {
      id: 17,
      title: 'Fahrenheit 451',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/d/db/Fahrenheit_451_1st_ed_cover.jpg/220px-Fahrenheit_451_1st_ed_cover.jpg',
      author: 'Ray Bradbury',
      category: 'Sci-Fi',
      description: 'A dystopian novel where books are outlawed.',
      rating: 4.4,
    },
    {
      id: 18,
      title: 'Thinking, Fast and Slow',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Thinking%2C_Fast_and_Slow.jpg/220px-Thinking%2C_Fast_and_Slow.jpg',
      author: 'Daniel Kahneman',
      category: 'Non-Fiction',
      description: 'An exploration of the two systems that drive human thought.',
      rating: 4.5,
    },
    {
      id: 19,
      title: 'The Picture of Dorian Gray',
      image:'https://almabooks.com/wp-content/uploads/2016/10/9781847493729-600x930.jpg',
      author: 'Oscar Wilde',
      category: 'Fiction',
      description: 'A novel about vanity, sin, and consequences.',
      rating: 4.3,
    },
    {
      id: 20,
      title: 'A Brief History of Time',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/BriefHistoryTime.jpg/220px-BriefHistoryTime.jpg',
      author: 'Stephen Hawking',
      category: 'Non-Fiction',
      description: 'An exploration of the universe and black holes.',
      rating: 4.4,
    },
    {
      id: 21,
      title: 'The Handmaid’s Tale',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/1/18/TheHandmaidsTale%281stEd%29.jpg/220px-TheHandmaidsTale%281stEd%29.jpg',
      author: 'Margaret Atwood',
      category: 'Fiction',
      description: 'A dystopian story of a woman’s struggle in a patriarchal society.',
      rating: 4.5,
    },
    {
      id: 22,
      title: 'Harry Potter and the Sorcerer’s Stone',
      image:'https://d5i0fhmkm8zzl.cloudfront.net/9780545790352_2.jpg',
      author: 'J.K. Rowling',
      category: 'Fantasy',
      description: 'The beginning of Harry Potter’s adventures.',
      rating: 4.8,
    },
    {
      id: 23,
      title: 'The Subtle Art of Not Giving a f**k',
      image:'https://media.shortform.com/covers/png/the-subtle-art-of-not-giving-a-fck-cover@8x.png',
      author: 'Mark Manson',
      category: 'Non-Fiction',
      description: 'A self-help guide on embracing life’s challenges.',
      rating: 4.2,
    },
    {
      id: 24,
      title: 'The Art of War',
      image:'https://cdn2.penguin.com.au/covers/original/9780877734529.jpg',
      author: 'Sun Tzu',
      category: 'Non-Fiction',
      description: 'Ancient wisdom on strategy and warfare.',
      rating: 4.3,
    },
    {
      id: 25,
      title: 'Jane Eyre',
      image:'https://th.bing.com/th/id/OIP.S6RKGdL1CMPMdj0exmv2agHaL0?w=186&h=297&c=7&r=0&o=5&pid=1.7',
      author: 'Charlotte Brontë',
      category: 'Fiction',
      description: 'A classic tale of resilience and love.',
      rating: 4.6,
    },
    {
      id: 26,
      title: 'Frankenstein',
      image:'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982146160/frankenstein-9781982146160_hr.jpg',
      author: 'Mary Shelley',
      category: 'Fiction',
      description: 'The story of a scientist and his monstrous creation.',
      rating: 4.3,
    },
    {
      id: 27,
      title: 'The Secret Life of Bees',
      image:'https://upload.wikimedia.org/wikipedia/en/1/1f/The_Secret_Life_of_Bees.jpg',
      author: 'Sue Monk Kidd',
      category: 'Fiction',
      description: 'A tale of a girl’s journey to find belonging.',
      rating: 4.7,
    },
    {
      id: 28,
      title: 'The Book Thief',
      image:'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/The_Book_Thief_by_Markus_Zusak_book_cover.jpg/220px-The_Book_Thief_by_Markus_Zusak_book_cover.jpg',
      author: 'Markus Zusak',
      category: 'Fiction',
      description: 'A story of a young girl during World War II.',
      rating: 4.8,
    },
    {
      id: 29,
      title: 'Guns, Germs, and Steel',
      image:'https://upload.wikimedia.org/wikipedia/en/f/fc/Ggas_human_soc.jpg',
      author: 'Jared Diamond',
      category: 'Non-Fiction',
      description: 'An analysis of the factors influencing human societies.',
      rating: 4.5,
    },
  ];
  